server:
  port: 5001
  servlet:
    context-path: /api
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
      default-filters:
        - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
