server:
  port: 5004
  servlet:
    context-path: /order

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?timeZone=UTC
    username: root
    password: r00t
  jpa:
    hibernate:
      ddl-auto: update