server:
  port: 5003
  servlet:
    context-path: /product

spring:
  datasource:
    username: root
    password: r00tme
    url: jdbc:mysql://mall:3306/product?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: product-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka
